version: '3.7'

services:
  blog:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,192.168.43.50
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8090:8090"
    depends_on:
      - blog

volumes:
  static_data:
